general {
    before_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})' && hyprsunset --identity
}

listener {
    timeout = 300
    on-timeout = hyprsunset --gamma 65 --temperature 3800
    on-resume = hyprsunset --identity
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})' && hyprsunset --identity
}
